### PR TITLE
FIX augmentSQL func to be compatible with 3.2 method signature

### PR DESCRIPTION
**Pull request by dhensby**
fixes a strict notice error that I get

### CODE REVIEW

**Comment by camfindlay** [comment]
Take it we'll be making master the 3.2 compat branch @dhensby ?

**Comment by dhensby** [comment]
Well, I assume so, otherwise there won't be anywhere for 3.2 compat to go?

**Comment by dhensby** [comment]
bump

**Comment by camfindlay** [comment]
take it the travis fails here are misleading?

**Pull request merged**
