### PR TITLE
FIX: Make subscribe selector more generic

### PR DESCRIPTION
**Pull request by gordonbanderson**
Fix for #182

### CODE REVIEW

**Comment by camfindlay** [comment]
@gordonbanderson thanks for these. Should have time tomorrow to look over. On an aside I/we need to check to make sure the master branch is in good shape compared to the 0.8 current stable. I think there was a few experiments that took place that we needed to revert/correct before a bit of progression on this module.

**Comment by camfindlay** [comment]
@dhensby do you remember where we got to with master branch on this module I remember we had a few things reverted etc. I wonder if we should simple make a copy of 0.8, cherry pick any thing the went on to master worth keeping and push up as the new master to move forward?

**Comment by dhensby** [comment]
@camfindlay I can't remember to be honest - all I recall is it being a complete mine-field and me thinking it needs a re-write ;)

**Comment by camfindlay** [comment]
All good @dhensby in that case would you be ok with my above decision to go back to drawing board on master branch? (I have a bit of time tomorrow NZDT to pick through the mess ;) )

**Comment by gordonbanderson** [comment]
Ah so are you saying the master branch is a mess...?  I have the same fix applied to 0.8.1, would this be more suitable as a PR?

**Comment by dhensby** [comment]
> All good @dhensby in that case would you be ok with my above decision to go back to drawing board on master branch? (I have a bit of time tomorrow NZDT to pick through the mess ;) )

yep :)

**Comment by gordonbanderson** [comment]
The user profile viewing and also registration is broken on the master branch so I've switched to 0.8 - worth reporting or not?  If you are going to revamp/replace master I guess not.

**Comment by camfindlay** [comment]
@gordonbanderson if they are bug fixes only (and don't introduce a new feature or something that might cause breaks for people relying on APIs in 0.8 branch) then PRs against the 0.8 branch is the right place. 

I'm going to be making a "develop" branch today that will eventually replace the current master branch (as we ended up getting that into a bit of a mess). This should allow us to move forward more easily.

**Comment by camfindlay** [comment]
A develop branch is up, cheery picked in some low hanging fruit, @dhensby I've left off you large template + structural change commit which was the one I think ended up causing grief a while back.

Seems still some failing tests on that branch which we'll want to resolve before this becomes new master.

**Comment by camfindlay** [comment]
Tests passing locally though.

**Comment by camfindlay** [comment]
Ok after half a day of battling this, here is what we've decided on #185

**Comment by gordonbanderson** [comment]
Fix up at https://github.com/silverstripe/silverstripe-forum/pull/187

**Pull request closed without merging**
