### PR TITLE
Test against 3, doc improvements and removed duplicated feature

### PR DESCRIPTION
**Pull request by camfindlay**

### CODE REVIEW

**Comment by camfindlay** [comment]
@dhensby master has been refreshed with 0.8 branch ready to start accepting pull requests. This updates the CI to test against 3.3 (forum should be compat with 3.x minor.

**Comment by camfindlay** [comment]
Since master passes against 3.1 core and this fails I suspect a regression in core needs addressing (either in core or here).

**Comment by camfindlay** [comment]
! outstanding test fail, passes in 3.1 not in 3.2+ need some help tracking down the cause of this one.

**Comment by dhensby** [comment]
Ping me again on Monday and I'll see if I can take a look

**Comment by camfindlay** [comment]
Morning @dhensby if you get a chance see if you can discover the issue between 3.1 and 3.2+ on that failing test. recken something in core giving us grief ;)

**Comment by dhensby** [comment]
argh! Ping me in your evening!

**Comment by camfindlay** [comment]
@dhensby ping :+1:

**Comment by dhensby** [comment]
@camfindlay sorry for the delay - pushed a fix up - the country dropdown was failing validation and so the assertion failed.

I added a temp translation for the "choose country" string - that'll need adding to all the languages

**Comment by camfindlay** [comment]
@dhensby been a while what was needed to resolve this PR?

**Comment by micmania1** [comment]
Lost in the abyss. Closing.

**Comment by camfindlay** [comment]
kill it with fire 🔥 🔥 🔥 🚒

**Pull request closed without merging**
