### PR TITLE
Improved translation support and German translations.

### PR DESCRIPTION
**Pull request by camfindlay**
Rebase of #88 on the 0.8 branch.

### CODE REVIEW

**Comment by camfindlay** [comment]
I think the translations need to come via transifex?

**Comment by dhensby** [comment]
@tractorcow?

**Comment by tractorcow** [comment]
I can manually merge, but I'll need to run a few tx commands and do a manual review for this.

@camfindlay this needs rebasing first please.

**Comment by camfindlay** [comment]
Will need a rebase on 0.8

**Comment by micmania1** [comment]
Not sure what's left on here but no response since 2016. Closing but feel free to re-open if this is still relevant.

**Pull request closed without merging**
