### PR TITLE
ENHANCEMENT Added beforePostMessage hook

### PR DESCRIPTION
**Pull request by camfindlay**
Intension is to leverage this hook to do pattern detection on potentially spammy posts.
First use case is for a spam keyword detection module DataExtension at https://github.com/camfindlay/silverstripe-suspendspammer/blob/features/checkpostforspam/code/SuspendSpammerForumControllerExtension.php

### CODE REVIEW

**Comment by dhensby** [comment]
Is a hook at this point necessary? Perhaps really it should be the validation that fails?

I'm not completely clear on the best practice for forms, but generally I go by "once it gets to the submission handler it's been accepted and shouldn't fail".

With `SpamProtector` the field checks if it's spammy and rejects at the validation stage, perhaps a more generic "onValidationFailure" hook in core would be helpful (if it doesn't already exist or isn't already accessible)?

Looking at your controller, I do think it's something that should be dealt with at validation time.

**Comment by camfindlay** [comment]
Hey @dhensby if I was intending to totally block the spam then yes that would be good. 

In my particular case I still want the post to occur and perform an action based on intercepting and inspecting the content (ghost a spammer). This is also in case we get false positives I can quickly return the user to a proper user state and their post would not be lost (I already do this on the registration form for forum).

**Comment by dhensby** [comment]
Ah, I see, clever.

And I just looked at the function - looks like it's taking on a TON of validation responsibility!

**Comment by dhensby** [comment]
You probably want to do this BEFORE the content and title are filtered and you probably want to check both the title and the content too. Otherwise you could have a spammy title and legit content and you wouldn't catch them.

It's a shame that the form handler is on the controller and not it's own Form class as that would allow you to extend the class and just overload the submit handler.

As an interim fix this looks good

**Comment by camfindlay** [comment]
Great so if I push up the suggested changes you'd be happy to merge?

**Comment by camfindlay** [comment]
@dhensby quick question, should the hook accept $member to pass the current member that is posting through the hook or should I simply recall $member = Member::currentUser(); in my extension code?

**Comment by dhensby** [comment]
Well, the current functionality does just use `Member::currentUser()` but I supposed that the hook should take it as an argument in case that logic changes in the future

**Comment by camfindlay** [comment]
I've altered the PR to simply pass on the $data, if in the future this changes (we have to do some work to make this module 3.2 compatible anyway) I can refactor to pass $member then.

**Comment by dhensby** [comment]
@camfindlay if you add the $member param now, then you're making the hooks written now more flexible for future changes, so I do think it should go in.

Adding it reduces the number of assumptions a developer of hooks needs to make in their code

**Comment by camfindlay** [comment]
Happy to merge if I make this change and update the PR shortly?

**Comment by camfindlay** [comment]
Updated.

**Comment by camfindlay** [comment]
high five :hand:

**Pull request merged**
