### PR TITLE
FIX: Link() methods referred to in SinglePost.ss now return an actual links

### PR DESCRIPTION
**Pull request by gordonbanderson**
Removed hardcoded links that SinglePost.ss uses, fixed templates accordingly

### CODE REVIEW

**Comment by camfindlay** [comment]
@gordonbanderson because this will introduce a breaking change, we'll have to look at releasing a major version once I get master into a good state. Definitely keen to include this though :D

**Comment by camfindlay** [comment]
@gordonbanderson master has been refreshed with 0.8, you'll want to rebase your work (or check if we haven't already fixed in 0.8). Thanks for your patience on this :)

**Comment by camfindlay** [comment]
Please rebase.

**Comment by gordonbanderson** [comment]
Replaced by PR #189

**Comment by gordonbanderson** [comment]
I note @camfindlay that the installation docs recommend the use of master...

https://github.com/silverstripe/silverstripe-forum/blob/master/docs/en/Installation.md

So there may be a few more broken forums out there than you hope.

**Pull request closed without merging**
