### PR TITLE
Adding extension hook to the end of getCMSFields in Forum and ForumHolde...

### PR DESCRIPTION
**Pull request by 3Dgoo**
Adding extension hook to the end of getCMSFields in Forum and ForumHolder to allow class extensions to edit existing field list.

### CODE REVIEW

**Comment by wilr** [comment]
@3Dgoo it's a little confusing but creating a new extension hook isn't the right way to go for this. Instead the code should be used to use beforeUpdateCMSFields. In fact, all code should be using that new API.

http://doc.silverstripe.org/en/developer_guides/extending/extensions#object-extension-injection-points

**Comment by 3Dgoo** [comment]
@wilr can `beforeUpdateCMSFields` be used to remove fields and tabs? For example I want to remove the _Categories_ tab and _ShowInCategories_ field in _ForumHolder_.

**Comment by wilr** [comment]
Forum / ForumHolder's entire method should be wrapped in a beforeUpdateCMSFields. Then extensions will run *after* that method.

**Comment by 3Dgoo** [comment]
Thanks for the information Will. Should I try the method of wrapping all the fields in a beforeUpdateCMSFields and submitting a pull request with those changes?

**Pull request closed without merging**
