### PR TITLE
FIX title validation for first post in forums

### PR DESCRIPTION
**Pull request by camfindlay**
Implemented #125 recommendations, this fixes bug #124 and doesn't alter any api's so shuold be safe for a patch level release on 0.7.x

@dhensby can you confirm this was what you had in mind?

### CODE REVIEW

**Comment by camfindlay** [comment]
Smoke test on this reveals a reply to a post still fires the required title, will look into this and update the PR.

**Comment by camfindlay** [comment]
Have been going around in circles on this and cannot seem to work out the solve. Logic looks like it should work however when submitting the form from the reply action the validator still seems to kick in on the Title form input (even though it shouldn't). Maybe I'm missing something around form submission in SS?

**Comment by dhensby** [comment]
@camfindlay you still need to handle strings coming into `$addMode`

See https://github.com/silverstripe/silverstripe-forum/blob/c1f16661f1e94913343a3400ab4524de467a1d92/code/pagetypes/Forum.php#L735-L737

I think you need:

```php
if ($addMode && strtolower($addMode) == 'false') {
    $addMode = false;
}
```

**Comment by camfindlay** [comment]
Updated as above @dhensby - can you test to see if this actually fixes the 0.7 bug? (Will forward port this up to 0.8 if it sorts problem of blank title threads.

**Comment by dhensby** [comment]
Fix confirmed

**Comment by dhensby** [comment]
Merged up into 0.8

**Comment by dhensby** [comment]
Ok, so this is a really bad piece of arcitecture.

The `PostMessageForm` function is not only used to render the form in the template, but also to handle the request to the controller. Which means the first argument can/should be a `SS_HTTPReqest` object - which is why the test is failing.

We can put in a basic `is_object()` test to protect against the problem, but ultimately we then don't know if the form should be in add mode or not...

**Pull request merged**
