### PR TITLE
Adding hook to extend Forum AdminFormFeatures.

### PR DESCRIPTION
**Pull request by 3Dgoo**

### CODE REVIEW

**Comment by 3Dgoo** [comment]
Is there anything I can do to help this pull request get through?

**Comment by dhensby** [comment]
In it goes

**Comment by dhensby** [comment]
Sorry for the delay @tractorcow will this need to move into 0.8 too?

**Comment by camfindlay** [comment]
yeah probably needs ported  up to 0.8, still a few more pull requests to resolve before we get a 0.8 out I think.

**Pull request merged**
