### PR TITLE
Fixing forum reports.

### PR DESCRIPTION
**Pull request by 3Dgoo**
The forum reports were not working. I have fixed up the code so that the reports work.

### CODE REVIEW

**Comment by edlinklater** [comment]
Thanks @3Dgoo, I've given this a test and it seems to work a charm.

**Comment by 3Dgoo** [comment]
Thanks @edlinklater . If I wanted to put this fix to the 0.7 branch as well would I do a new branch off 0.7, commit my changes and submit a new pull request?

**Comment by edlinklater** [comment]
@3Dgoo: Yes please, that way the tests are run automatically. Don't worry about master though, we'll merge it forward from 0.8.

**Comment by 3Dgoo** [comment]
Awesome. I'll get on to that now. Let me know if I get any of the process wrong.

**Pull request merged**
