### PR TITLE
Wrapping getCMSFields fields with beforeUpdateCMSFields.

### PR DESCRIPTION
**Pull request by 3Dgoo**
Wrapping getCMSFields fields with beforeUpdateCMSFields to allow extensions to run after fields have been added. This allows Forum and ForumHolder fields to be modified or removed in extensions.

### CODE REVIEW

**Comment by camfindlay** [comment]
Just to check whether this should actually be part of a 0.8 release... is there any potential for this to cause a breaking change?

**Comment by camfindlay** [comment]
Say for instance if someone has already applied a DataExtension in the old way and removed some form components using removeByName() etc

**Comment by dhensby** [comment]
It's definitely a change of behaviour and not something to make a patch release. It's potentially a major release given I don't see how this isn't a breaking change (to existing functionality).

Where is `beforeUpdateCMSFields` coming from?

**Comment by wilr** [comment]
@dhensby FYI http://doc.silverstripe.org/en/developer_guides/extending/extensions#object-extension-injection-points

I'm happy for this to merge as it is a bug. Extensions cannot modify the core fields. If anyones relying on extensions not modifying Forum that would be unique.

**Comment by dhensby** [comment]
> @dhensby FYI http://doc.silverstripe.org/en/developer_guides/extending/extensions#object-extension-injection-points

:mind_blown:

> I'm happy for this to merge as it is a bug. Extensions cannot modify the core fields. If anyones relying on extensions not modifying Forum that would be unique.

It's really a missing feature, not a bug with an existing one. I suppose the question is not if it's a bug or not, it's about whether any public APIs are broken (as that's what SemVer is about).

I'd say it does because the fields returned by the hook are part of the API BUT it's changed in a BC way (there are just new fields, we aren't removing any that one would expect to be there previously).

Therefore, this should be a 0.8 release, not a 0.7.x

**Comment by tractorcow** [comment]
I think it should be 0.8, but I'm not finicky about it, since forum isn't (strictly) on semantic versioning. :P

It's a "let users extend core fields" which seems to be a usability enhancement to an existing API, so it should go into the next minor version (0.8).

**Comment by camfindlay** [comment]
0.8 sounds good, @3Dgoo can you pull request this against master branch and we'll look to make a 0.8.0 soon then.

**Comment by 3Dgoo** [comment]
Hi @camfindlay, I've created a new pull request for this against master as requested: 
https://github.com/silverstripe/silverstripe-forum/pull/128

**Comment by camfindlay** [comment]
thanks, I have since found that @tractorcow updated master to track against the future 3.2 release, so what I might do is accept the merge onto master as is then backport onto a new 0.8 branch which is based off 0.7 (as there are some 0.7 pull requests I still need to address and then forward port thos onto 0.8). This way things will work with 3.1 SS core. Any objections to this approach @dhensby or is there an easier way to deal with this?

**Pull request closed without merging**
