### PR TITLE
Moved user docs into userguide folder to display on userhelp site

### PR DESCRIPTION
**Pull request by mandrew**
moved docs from user help site, restructured docs to separate files, moved images and added index.md file

### CODE REVIEW

**Comment by camfindlay** [comment]
@SpiritLevel these prefixes are used by the docsviewer module to order the content.

**Comment by SpiritLevel** [comment]
Ah, OK....but if those prefixes get encoded into links within other .md files it may make reorganising later painful...I noticed this problem with the older written tutorials.

**Comment by camfindlay** [comment]
Those tutorial prefixes in framework were legacy and unrelated to this.

**Comment by SpiritLevel** [comment]
OK...I see how the docsviewer code handles the prefixes :)

**Pull request merged**
