### PR TITLE
Template fixes

### PR DESCRIPTION
**Pull request by dhensby**
- Fixing template syntax and a few bugs
- Deprecating the `$limit` param from `LatestMembers` - template can do `$LatestMembers.First`, etc

### CODE REVIEW

**Comment by dhensby** [comment]
anyone? - tests are strict standards issues and related to changes in framework

**Comment by camfindlay** [comment]
could these go on the 0.8 branch @dhensby ? I'd like to do a release sometime soon of this (think there is 1 outstanding items I'd like tackled on 0.8 the stats not correctly calculating).

**Comment by dhensby** [comment]
I can probably merge this into 0.8 once it get's in ;)

**Comment by camfindlay** [comment]
Will you back port this to 0.8 @dhensby ? Also if you have a moment I have some other 0.8 related PRs you could peer :)

**Pull request merged**
